name: Test, Build, Deploy

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: ${{ github.ref_name }}

      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'

      - name: Install Dependencies
        run: npm ci

      - name: Test
        run: npm run test

      - name: Compile SASS Files
        uses: gha-utilities/sass-build@v0.5.1
        with:
          source: "./public/resources/css/leaflet.scss"
          destination: "./public/resources/css/leaflet.min.css"

      - name: Build
        run: npm run build

      - name: Upload Artifact
        uses: actions/upload-pages-artifact@v1
        with:
          path: "./build"

  deploy:
    needs: [build]

    permissions:
      pages: write
      id-token: write

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    runs-on: ubuntu-latest
    steps: 
      - name: Deploy
        id: deployment
        uses: actions/deploy-pages@v2